name: Update epg

on:
  workflow_dispatch:
  repository_dispatch:
    types: [epg_update]
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Repository
        env:
          TOKEN: ${{ secrets.PAT }}
          REPO: ${{ secrets.REPO }}
        run: |
          git clone "https://${TOKEN}@github.com/${REPO}.git" epg-folder --depth 1

      - name: Copy output
        run: |
          cp epg-folder/README.md README.md
          rm -rf e
          cp -r epg-folder/e e
          rm -rf epg-folder

      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update" || echo "Nothing to commit"
          git push
